# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: housing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'housing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhousing.proto\x12\x07housing\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\x05Stats\x12\x12\n\ntotal_rows\x18\x01 \x01(\x03\"\"\n\x06MaxMin\x12\x0b\n\x03max\x18\x01 \x01(\x01\x12\x0b\n\x03min\x18\x02 \x01(\x01\"\xf0\x02\n\x08Metadata\x12\x1e\n\x05Price\x18\x01 \x01(\x0b\x32\x0f.housing.MaxMin\x12!\n\x08\x42\x65\x64rooms\x18\x02 \x01(\x0b\x32\x0f.housing.MaxMin\x12\"\n\tBathrooms\x18\x03 \x01(\x0b\x32\x0f.housing.MaxMin\x12#\n\nSquareFeet\x18\x04 \x01(\x0b\x32\x0f.housing.MaxMin\x12\"\n\tYearBuilt\x18\x05 \x01(\x0b\x32\x0f.housing.MaxMin\x12%\n\x0cGarageSpaces\x18\x06 \x01(\x0b\x32\x0f.housing.MaxMin\x12 \n\x07LotSize\x18\x07 \x01(\x0b\x32\x0f.housing.MaxMin\x12 \n\x07ZipCode\x18\x08 \x01(\x0b\x32\x0f.housing.MaxMin\x12\"\n\tCrimeRate\x18\t \x01(\x0b\x32\x0f.housing.MaxMin\x12%\n\x0cSchoolRating\x18\n \x01(\x0b\x32\x0f.housing.MaxMin2~\n\x0eHousingService\x12\x32\n\x08GetStats\x12\x16.google.protobuf.Empty\x1a\x0e.housing.Stats\x12\x38\n\x0bGetMetadata\x12\x16.google.protobuf.Empty\x1a\x11.housing.Metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'housing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATS']._serialized_start=55
  _globals['_STATS']._serialized_end=82
  _globals['_MAXMIN']._serialized_start=84
  _globals['_MAXMIN']._serialized_end=118
  _globals['_METADATA']._serialized_start=121
  _globals['_METADATA']._serialized_end=489
  _globals['_HOUSINGSERVICE']._serialized_start=491
  _globals['_HOUSINGSERVICE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
